#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npx lint-staged

# Check code formatting with Prettier
npm run check-format || (
    echo "\n❌ Prettier Check Failed.❌\n Please run 'npm run format', add the changes, and try committing again.👀 \n"
    false
)

# Check Types Standards
npm run check-types || (
    echo "\n❌ Type Check Failed.❌\n Make the required changes listed above, add the changes, and try committing again.👀 \n"
    false
)

# If everything passes, we can now commit
echo "✅ Commit Hook Passed! Committing changes now. 💪\n"
